#name: learn-github-actions
#on: [push]
#jobs:
 # check-bats-version:
  #  runs-on: ubuntu-latest
   # steps:
    #  - uses: actions/checkout@v3
    # - uses: actions/setup-node@v3
    #    with:
    #      node-version: '14'
    #  - run: npm install -g bats
    #  - run: bats -v
name: Node.js CI

on:
  push:
    branches: [ feature/** ]
   
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: node greetPerson.js
      
      # !! Merge request starts from here
      - title: Assign Yourself
        description: Assign yourself to the first issue in this repository.
        event: issues.assigned
        link: "{{ repoUrl }}/issues/1"
        actions:
          - type: gate
            left: "%payload.assignee.login%"
            operator: ===
            right: "%user.username%"
          - type: createPullRequest
            title: Add some comment
            body: Seems all OK
          - type: closeIssue
            issue: Welcome      

      - title: Approve a pull request
        description: Approve the pull request so that it can be merged.
        event: pull_request_review.submitted
        link: "{{ repoUrl }}/pull/2"
        actions:
          - type: gate
            left: "%payload.review.state%"
            operator: ===
            right: "approved"
          - type: mergeBranch
            head: feature/**            

        - title: Merge the pull request
          description: Merge the pull request after applying the suggested change.
          event: pull_request.closed
          link: "{{ repoUrl }}/pulls"
          actions:
          - type: gate
            left: "%payload.pull_request.merged%"
            