name: Merge PR into Main

on:
  push:
    branches: [release/**]

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    if: ${{ contains(github.event.*.labels.*.name, 'merge into main') }}
    name: Merge Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.push.head.ref }}
          fetch-depth: 0

      - name: perform merge
        run: |
          git config --global user.email "${pankaj@rainfall.one}"
          git config --global user.name "${rainfall-pankaj}"
          git status
          git pull
          git checkout "$GITHUB_HEAD_REF"
          git status
          git pull
          git checkout "$DEFAULT_BRANCH"
          git merge "$GITHUB_HEAD_REF" --no-edit
          git push
          git status
      # https://github.com/marketplace/actions/actions-ecosystem-remove-labels
      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: merge into main