name: Automerge

on:
  push:
    branches:
      - 'release/**'

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://github.com/rainfall-pankaj/WebsiteTesting.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: release\test\pankaj3

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/rainfall-pankaj/WebsiteTesting.git

  # replace "master" with your master branch name
  MASTER_BRANCH: main

  RELEASE_BRANCH: 'release/**'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with main
      run: |
        git config user.name "rainfall-pankaj"
        git config user.email "pankaj@rainfall.one"
        git add .
        git stash
        git switch ${{env.MASTER_BRANCH}}
        git pull
        git switch ${{env.RELEASE_BRANCH}}
        git merge
        git stash apply
        git push --set-upstream origin ${{env.RELEASE_BRANCH}}